services:
  worker1:
    image: docker:dind
    privileged: true
    container_name: worker1
    environment:
      - DOCKER_TLS_CERTDIR=/certs
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - worker1-certs:/certs
      - worker1-data:/var/lib/docker
    networks:
      - swarm-network

  worker2:
    image: docker:dind
    privileged: true
    container_name: worker2
    environment:
      - DOCKER_TLS_CERTDIR=/certs
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - worker2-certs:/certs
      - worker2-data:/var/lib/docker
    networks:
      - swarm-network

volumes:
  worker1-certs:
  worker1-data:
  worker2-certs:
  worker2-data:

networks:
  swarm-network:
    driver: overlay
    attachable: true