services:
  worker1:
    build:
      context: ./node1/
      dockerfile: Dockerfile
    privileged: true
    container_name: worker1
    ports:
      - "2555:2555"
    environment:
      - JOIN_TOKEN=${JOIN_TOKEN}
      - MANAGER_IP=${MANAGER_IP}
    volumes:
      - worker1-certs:/certs
    networks:
      - swarm-network

  worker2:
    build:
      context: ./node2/
      dockerfile: Dockerfile
    privileged: true
    container_name: worker2
    ports:
      - "2551:2551"
    environment:
      - JOIN_TOKEN=${JOIN_TOKEN}
      - MANAGER_IP=${MANAGER_IP}
    volumes:
      - worker2-certs:/certs
    networks:
      - swarm-network

volumes:
  worker1-certs:
  worker2-certs:

networks:
  swarm-network:
    driver: overlay
    attachable: true