services:
  worker1:
    build:
      context: ./node1/
      dockerfile: Dockerfile
    privileged: true
    container_name: worker1
    ports:
      - "2555:2555"
    environment:
      - DOCKER_TLS_CERTDIR=/certs
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - worker1-certs:/certs
      - worker1-data:/var/lib/docker
    networks:
      - swarm-network

  worker2:
    build:
      context: ./node2/
      dockerfile: Dockerfile
    privileged: true
    container_name: worker2
    ports:
      - "2551:2551"
    environment:
      - DOCKER_TLS_CERTDIR=/certs
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - worker2-certs:/certs
      - worker2-data:/var/lib/docker
    networks:
      - swarm-network

volumes:
  worker1-certs:
  worker1-data:
  worker2-certs:
  worker2-data:

networks:
  swarm-network:
    driver: overlay
    attachable: true