pages = [{"l":"index.html#","e":false,"i":"","n":"node1 API","t":"node1 API","d":"","k":"static","x":""},
{"l":"org/example.html#","e":false,"i":"","n":"org.example","t":"org.example","d":"","k":"package","x":""},
{"l":"org/example/api.html#","e":false,"i":"","n":"org.example.api","t":"org.example.api","d":"","k":"package","x":""},
{"l":"org/example/api/discovery.html#","e":false,"i":"","n":"org.example.api.discovery","t":"org.example.api.discovery","d":"","k":"package","x":""},
{"l":"org/example/api/discovery/ServiceKeys$.html#","e":false,"i":"","n":"ServiceKeys","t":"ServiceKeys","d":"org.example.api.discovery","k":"object","x":""},
{"l":"org/example/api/discovery/ServiceKeys$.html#PingServiceKey-0","e":false,"i":"","n":"PingServiceKey","t":"PingServiceKey: ServiceKey[Message]","d":"org.example.api.discovery.ServiceKeys","k":"val","x":""},
{"l":"org/example/api/discovery/ServiceKeys$.html#PongServiceKey-0","e":false,"i":"","n":"PongServiceKey","t":"PongServiceKey: ServiceKey[Message]","d":"org.example.api.discovery.ServiceKeys","k":"val","x":""},
{"l":"org/example/api/protocol.html#","e":false,"i":"","n":"org.example.api.protocol","t":"org.example.api.protocol","d":"","k":"package","x":""},
{"l":"org/example/api/protocol/Message.html#","e":false,"i":"","n":"Message","t":"Message","d":"org.example.api.protocol","k":"trait","x":""},
{"l":"org/example/api/protocol/Ping.html#","e":false,"i":"","n":"Ping","t":"Ping(replyTo: ActorRef[Pong]) extends Message","d":"org.example.api.protocol","k":"class","x":""},
{"l":"org/example/api/protocol/Pong.html#","e":false,"i":"","n":"Pong","t":"Pong(replyTo: ActorRef[Ping]) extends Message","d":"org.example.api.protocol","k":"class","x":""},
{"l":"org/example/App$.html#","e":false,"i":"","n":"App","t":"App","d":"org.example","k":"object","x":""},
{"l":"org/example/App$.html#main-913","e":false,"i":"","n":"main","t":"main(args: Array[String]): Unit","d":"org.example.App","k":"def","x":""},
{"l":"org/example/App$$FindPong$.html#","e":false,"i":"","n":"FindPong","t":"FindPong extends Message","d":"org.example.App","k":"object","x":""},
{"l":"org/example/App$$Start$.html#","e":false,"i":"","n":"Start","t":"Start extends Message","d":"org.example.App","k":"object","x":""},
{"l":"org/example/WorkerTwo$.html#","e":false,"i":"","n":"WorkerTwo","t":"WorkerTwo","d":"org.example","k":"object","x":""},
{"l":"org/example/WorkerTwo$.html#apply-5c0","e":false,"i":"","n":"apply","t":"apply(): WorkerTwo","d":"org.example.WorkerTwo","k":"def","x":""},
{"l":"org/example/WorkerTwo$.html#pingSelfRef-0","e":false,"i":"","n":"pingSelfRef","t":"pingSelfRef: Option[ActorRef[Message]]","d":"org.example.WorkerTwo","k":"var","x":""},
{"l":"org/example/WorkerTwo.html#","e":false,"i":"","n":"WorkerTwo","t":"WorkerTwo","d":"org.example","k":"class","x":""},
{"l":"org/example/WorkerTwo.html#behavior-2bd","e":false,"i":"","n":"behavior","t":"behavior(): Behavior[Message]","d":"org.example.WorkerTwo","k":"def","x":""}];