pages = [{"l":"index.html#","e":false,"i":"","n":"node2 API","t":"node2 API","d":"","k":"static","x":""},
{"l":"org/example.html#","e":false,"i":"","n":"org.example","t":"org.example","d":"","k":"package","x":""},
{"l":"org/example/api.html#","e":false,"i":"","n":"org.example.api","t":"org.example.api","d":"","k":"package","x":""},
{"l":"org/example/api/discovery.html#","e":false,"i":"","n":"org.example.api.discovery","t":"org.example.api.discovery","d":"","k":"package","x":""},
{"l":"org/example/api/discovery/ServiceKeys$.html#","e":false,"i":"","n":"ServiceKeys","t":"ServiceKeys","d":"org.example.api.discovery","k":"object","x":""},
{"l":"org/example/api/discovery/ServiceKeys$.html#PingServiceKey-0","e":false,"i":"","n":"PingServiceKey","t":"PingServiceKey: ServiceKey[Message]","d":"org.example.api.discovery.ServiceKeys","k":"val","x":""},
{"l":"org/example/api/discovery/ServiceKeys$.html#PongServiceKey-0","e":false,"i":"","n":"PongServiceKey","t":"PongServiceKey: ServiceKey[Message]","d":"org.example.api.discovery.ServiceKeys","k":"val","x":""},
{"l":"org/example/api/protocol.html#","e":false,"i":"","n":"org.example.api.protocol","t":"org.example.api.protocol","d":"","k":"package","x":""},
{"l":"org/example/api/protocol/Message.html#","e":false,"i":"","n":"Message","t":"Message","d":"org.example.api.protocol","k":"trait","x":""},
{"l":"org/example/api/protocol/Ping.html#","e":false,"i":"","n":"Ping","t":"Ping(replyTo: ActorRef[Pong]) extends Message","d":"org.example.api.protocol","k":"class","x":""},
{"l":"org/example/api/protocol/Pong.html#","e":false,"i":"","n":"Pong","t":"Pong(replyTo: ActorRef[Ping]) extends Message","d":"org.example.api.protocol","k":"class","x":""},
{"l":"org/example/App$.html#","e":false,"i":"","n":"App","t":"App","d":"org.example","k":"object","x":""},
{"l":"org/example/App$.html#main-913","e":false,"i":"","n":"main","t":"main(args: Array[String]): Unit","d":"org.example.App","k":"def","x":""},
{"l":"org/example/App$$FindPing$.html#","e":false,"i":"","n":"FindPing","t":"FindPing extends Message","d":"org.example.App","k":"object","x":""},
{"l":"org/example/App$$Start$.html#","e":false,"i":"","n":"Start","t":"Start extends Message","d":"org.example.App","k":"object","x":""},
{"l":"org/example/WorkerOne$.html#","e":false,"i":"","n":"WorkerOne","t":"WorkerOne","d":"org.example","k":"object","x":""},
{"l":"org/example/WorkerOne$.html#apply-1da","e":false,"i":"","n":"apply","t":"apply(): WorkerOne","d":"org.example.WorkerOne","k":"def","x":""},
{"l":"org/example/WorkerOne$.html#pongSelfRef-0","e":false,"i":"","n":"pongSelfRef","t":"pongSelfRef: Option[ActorRef[Message]]","d":"org.example.WorkerOne","k":"var","x":""},
{"l":"org/example/WorkerOne.html#","e":false,"i":"","n":"WorkerOne","t":"WorkerOne","d":"org.example","k":"class","x":""},
{"l":"org/example/WorkerOne.html#behavior-2bd","e":false,"i":"","n":"behavior","t":"behavior(): Behavior[Message]","d":"org.example.WorkerOne","k":"def","x":""}];