name: API Validation

on:
  push:
    branches: [main]

jobs:
  validate-api:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'corretto'
        java-version: '17'
        
    - name: Setup Development Environment
      run: ./gradlew devSetup
      
    - name: Validate API Compliance
      run: ./gradlew apiValidate
      
    - name: Check Project Status
      run: ./gradlew projectStatus
      
    - name: Generate API Documentation
      run: ./gradlew apiDocs
      
    - name: Upload API Documentation
      uses: actions/upload-artifact@v3
      with:
        name: api-documentation
        path: docs/api/generated/